"""
Observation fields and canonical phrase options for the L3 autoreport builder.
Each entry: key, display label, and dropdown options (appended to free-text on select).

Category order matches the Level 4 radiographic findings table layout.
"""

L3_AUTOREPORT_OBSERVATIONS = [
    {
        "key": "obstruction_sites",
        "label": "Obstruction Sites",
        "options": [
            "Significant multilevel upper airway narrowing involving the velopharyngeal region, oropharynx, and tongue base.",
            "Multilevel upper airway narrowing involving the velopharyngeal region, oropharynx, and tongue base.",
            "Multilevel upper airway narrowing involving the velopharyngeal region and tongue base.",
            "Multilevel upper airway narrowing involving the velopharyngeal region and oropharynx.",
            "Upper airway narrowing primarily at the velopharyngeal region, with secondary involvement of the tongue base.",
            "Upper airway narrowing primarily at the tongue base, with secondary involvement of the velopharyngeal region.",
            "Upper airway narrowing involving the velopharyngeal region.",
            "Upper airway narrowing involving the tongue base.",
            "No significant upper airway narrowing identified.",
        ],
    },
    {
        "key": "narrowest_airway",
        "label": "Narrowest Airway Point",
        "options": [
            "Marked reduction in airway calibre with combined anteroposterior and lateral narrowing.",
            "Reduced airway calibre with combined anteroposterior and lateral narrowing.",
            "Reduced airway calibre with predominantly anteroposterior narrowing.",
            "Reduced airway calibre with predominantly lateral narrowing.",
            "No significant focal airway narrowing identified.",
        ],
    },
    {
        "key": "soft_palate",
        "label": "Soft Palate & Uvula",
        "options": [
            "Elongated soft palate and uvula contributing to reduction of the retropalatal airway space.",
            "Elongated soft palate and bulky uvula contributing to reduction of the retropalatal airway space.",
            "Bulky uvula contributing to reduction of the retropalatal airway space.",
            "No significant soft palate or uvular enlargement identified.",
        ],
    },
    {
        "key": "palatal_soft_tissue",
        "label": "Palatal Soft Tissue (Hard Palate Region)",
        "options": [
            "Enlargement of soft tissue structures along the hard palate, contributing to reduced intraoral space and limited tongue accommodation.",
            "Prominent soft tissue structures along the hard palate contribute to reduced intraoral space.",
            "Asymmetric soft tissue enlargement is noted along the hard palate.",
            "No significant soft tissue abnormality is identified along the hard palate.",
        ],
    },
    {
        "key": "tongue_position",
        "label": "Tongue Position",
        "options": [
            "Enlarged tongue relative to available oral cavity volume, with a posteriorly positioned tongue base encroaching on the oropharyngeal airway.",
            "Posteriorly positioned tongue base encroaching on the oropharyngeal airway.",
            "Enlarged tongue relative to available oral cavity volume contributing to airway crowding.",
            "No significant tongue-related airway compromise identified.",
        ],
    },
    {
        "key": "bite_jaw",
        "label": "Bite & Jaw Structure",
        "options": [
            "High-arched maxilla",
            "Narrow maxilla",
            "High-arched, narrow maxilla",
            "Markedly narrow maxilla",
            "Markedly high-arched, narrow maxilla",
            "High-arched, narrow maxilla, more pronounced on one side",
            "Maxilla appears within normal limits.",
            "Narrow mandible",
            "Markedly narrow mandible",
            "Retruded mandible",
            "Retrognathic mandible",
            "Narrow, retruded mandible",
            "Markedly narrow, retruded mandible",
            "Mandible appears within normal limits.",
            "Increased overjet",
            "Excessive overjet",
            "Reduced overjet",
            "Normal overjet",
            "Increased overbite",
            "Excessive overbite",
            "Reduced overbite",
            "Normal overbite",
            "Deep bite",
            "Overclosed bite",
            "Anterior open bite",
            "Posterior open bite",
            "Anterior crossbite",
            "Posterior crossbite",
            "Right posterior crossbite",
            "Left posterior crossbite",
            "Edge-to-edge occlusal pattern",
            "Occlusal relationships cannot be reliably assessed due to open-mouth positioning during imaging.",
            "Lingually inclined mandibular molars",
            "Lingually tipped mandibular teeth",
            "Anterior inclination of the mandibular anterior teeth",
            "Steep proclination of the mandibular anterior dentition",
            "Narrow dental arches",
            "Markedly constricted maxillary and mandibular arches",
            "These findings contribute to reduced anteroposterior oral cavity volume.",
            "These findings contribute to reduced anteroposterior oral cavity volume and limited tongue space.",
        ],
    },
    {
        "key": "dental_findings",
        "label": "Dental Findings",
        "options": [
            "Signs of dental wear are noted.",
            "Significant dental wear is noted.",
            "Missing posterior teeth are noted.",
            "Missing anterior teeth are noted.",
            "Missing teeth are noted.",
            "Multiple restorations are noted.",
            "Multiple restorations and prosthetic elements are noted.",
            "Dental implants are present.",
            "Multiple dental implants are present.",
            "Extensive prosthetic rehabilitation is present.",
            "Mandibular arch crowding is noted.",
            "Generalized dental crowding is noted.",
            "Midline shift is noted.",
            "Interdental spacing is present.",
            "Open contact points are noted.",
            "Multiple open interproximal embrasures are noted.",
            "Flared maxillary anterior teeth are noted.",
            "Alveolar bone loss is noted.",
            "Alveolar bone loss affecting multiple teeth is noted.",
            "Reduced periodontal support is noted.",
        ],
    },
    {
        "key": "hyoid_bone",
        "label": "Hyoid Bone",
        "options": [
            "The hyoid bone is positioned significantly inferior to the mandibular plane.",
            "The hyoid bone is positioned inferior to the mandibular plane.",
            "The hyoid bone is positioned at the level of the mandibular plane.",
            "The hyoid bone is not fully visualized within the available field of view; however, it appears to be positioned inferior to the mandibular plane.",
        ],
    },
    {
        "key": "epiglottis",
        "label": "Epiglottis",
        "options": [
            "A retroflexed epiglottis is identified on sagittal views.",
            "A recurved epiglottic tip is identified on sagittal views.",
            "A retroflexed epiglottis with a recurved tip is identified on sagittal views.",
            "A recurved epiglottis is identified on axial views.",
            "An omega-shaped epiglottis is identified on axial views.",
            "No significant epiglottic abnormality identified.",
        ],
    },
    {
        "key": "tmj",
        "label": "Temporomandibular Joints (TMJ)",
        "options": [
            "Cortical continuity is preserved bilaterally.",
            "Cortical continuity is preserved bilaterally, with no significant osseous abnormality identified.",
            "Loss of cortical continuity is noted bilaterally.",
            "Focal cortical thinning of the roof of the glenoid fossa is noted.",
            "Condylar flattening is noted bilaterally.",
            "Significant condylar flattening is noted bilaterally.",
            "Condylar flattening is noted, greater on the right.",
            "Condylar flattening is noted, greater on the left.",
            "Bilateral temporomandibular joint remodeling is noted.",
            "Bilateral temporomandibular joint remodeling is noted, greater on the right.",
            "Bilateral temporomandibular joint remodeling is noted, greater on the left.",
            "Posterior positioning of the condyles within the glenoid fossae is noted bilaterally.",
            "Anterior positioning of the condyles within the glenoid fossae is noted bilaterally.",
            "Posterior positioning of the condyles within the glenoid fossae is noted, greater on the right.",
            "Posterior positioning of the condyles within the glenoid fossae is noted, greater on the left.",
            "Anterior positioning of the condyles within the glenoid fossae is noted, greater on the right.",
            "Anterior positioning of the condyles within the glenoid fossae is noted, greater on the left.",
            "Joint space narrowing is noted bilaterally.",
            "Joint space narrowing is noted, greater on the right.",
            "Joint space narrowing is noted, greater on the left.",
            "Advanced joint space narrowing is noted bilaterally.",
            "Areas of bone-to-bone approximation are noted.",
            "Irregular contour of the condylar heads is noted bilaterally.",
            "Irregular contour of the right condylar head is noted.",
            "Irregular contour of the left condylar head is noted.",
            "Subchondral cysts are noted bilaterally.",
            "Subchondral cysts are noted in the right condylar head.",
            "Subchondral cysts are noted in the left condylar head.",
            "Flattening of the articular eminence is noted.",
            "Significant flattening of the articular eminence is noted.",
            "Relatively slender condylar necks are noted bilaterally.",
            "Markedly slender condylar necks are noted bilaterally.",
            "Relatively slender condylar necks are noted, more pronounced on the right.",
            "Relatively slender condylar necks are noted, more pronounced on the left.",
            "Asymmetry between the temporomandibular joints is noted.",
            "The temporomandibular joints are not fully visualized within the available field of view.",
            "Assessment of condylar position within the fossae is limited due to mandibular positioning during imaging.",
            "Condylar position within the fossae cannot be reliably assessed due to open-mouth positioning during imaging.",
        ],
    },
    {
        "key": "nasal_sinus",
        "label": "Nasal & Sinus Findings",
        "options": [
            "Nasal septal deviation",
            "Rightward nasal septal deviation",
            "Leftward nasal septal deviation",
            "Mucosal thickening along the nasal septum",
            "Narrow nasal valves",
            "Relatively narrow nasal valves",
            "Bilateral nasal valve narrowing",
            "Narrow nasal cavity",
            "Nasal cavity asymmetry",
            "Relative narrowing of the right nasal cavity",
            "Relative narrowing of the left nasal cavity",
            "Mucosal thickening along the nasal floor",
            "Inferior turbinate hypertrophy",
            "Bilateral inferior turbinate hypertrophy",
            "Bilateral inferior turbinate hypertrophy, more prominent on the right",
            "Bilateral inferior turbinate hypertrophy, more prominent on the left",
            "Inferior turbinate hypertrophy on the right",
            "Inferior turbinate hypertrophy on the left",
            "Paradoxical middle turbinate",
            "Paradoxical right middle turbinate",
            "Paradoxical left middle turbinate",
            "Right concha bullosa",
            "Left concha bullosa",
            "Bilateral concha bullosa",
            "Bilateral maxillary sinus mucosal thickening",
            "Right maxillary sinus mucosal thickening",
            "Left maxillary sinus mucosal thickening",
            "Bilateral dome-shaped mucosal thickening within the maxillary sinuses",
            "Dome-shaped mucosal thickening within the right maxillary sinus",
            "Dome-shaped mucosal thickening within the left maxillary sinus",
            "Bilateral polypoid mucosal thickening within the maxillary sinuses",
            "Polypoid mucosal thickening within the right maxillary sinus",
            "Polypoid mucosal thickening within the left maxillary sinus",
            "Findings may be consistent with an odontogenic source",
            "Bilateral ethmoid sinus mucosal thickening",
            "Right ethmoid sinus mucosal thickening",
            "Left ethmoid sinus mucosal thickening",
            "Partial ethmoid air cell opacification",
            "Ethmoid air cell opacification",
            "Bilateral polypoid mucosal thickening within the ethmoid sinuses",
            "Polypoid mucosal thickening within the right ethmoid sinus",
            "Polypoid mucosal thickening within the left ethmoid sinus",
            "Bilateral frontal sinus mucosal thickening",
            "Right frontal sinus mucosal thickening",
            "Left frontal sinus mucosal thickening",
            "Bilateral polypoid mucosal thickening within the frontal sinuses",
            "Polypoid mucosal thickening within the right frontal sinus",
            "Polypoid mucosal thickening within the left frontal sinus",
            "Bilateral sphenoid sinus mucosal thickening",
            "Right sphenoid sinus mucosal thickening",
            "Left sphenoid sinus mucosal thickening",
            "Bilateral polypoid mucosal thickening within the sphenoid sinuses",
            "Polypoid mucosal thickening within the right sphenoid sinus",
            "Polypoid mucosal thickening within the left sphenoid sinus",
            "Frontal sinus drainage pathway appears obstructed",
            "Osteomeatal complex narrowing",
            "Osteomeatal complex obstruction",
            "No significant nasal or paranasal sinus abnormality is identified.",
        ],
    },
    {
        "key": "cervical_spine_alignment",
        "label": "Cervical Spine Alignment",
        "options": [
            "Mild straightening of the cervical spine curvature is noted.",
            "Straightening of the cervical spine curvature is noted.",
            "Straightening of the cervical spine curvature with relative anterior positioning of the head is noted.",
            "No significant cervical spine alignment abnormality is identified.",
        ],
    },
]

# Map canonical anatomy_imaging keys → autoreport observation keys
CANONICAL_TO_AUTOREPORT = {
    "primary_obstruction_site": "obstruction_sites",
    "soft_palate_uvula": "soft_palate",
    "tongue_base": "tongue_position",
    "bite_jaw": "bite_jaw",
    "hyoid": "hyoid_bone",
    "nose_sinus": "nasal_sinus",
    "narrowest_airway": "narrowest_airway",
    "epiglottis": "epiglottis",
    "tmj": "tmj",
    "dental_periodontal": "dental_findings",
    "dental_findings": "dental_findings",
    "hard_palate": "palatal_soft_tissue",
    "palatal_soft_tissue": "palatal_soft_tissue",
    "cervical_spine": "cervical_spine_alignment",
    "cervical_spine_alignment": "cervical_spine_alignment",
}
