"""
Stage Summary manifest configuration.

This file defines the ordered collection of stage descriptors used by the
stage summary API. Each entry should provide the metadata required to
evaluate completion status without embedding evaluation logic here.

Entries will be expanded in subsequent implementation phases. For now the
structure is scaffolded so that downstream components can import and iterate
over the manifest.
"""

from __future__ import annotations

from typing import List, TypedDict, Dict, Any

try:  # Python 3.11+
    from typing import NotRequired  # type: ignore[attr-defined]
except ImportError:  # Python <3.11
    try:
        from typing_extensions import NotRequired  # type: ignore
    except ImportError:
        class _CompatNotRequiredMeta(type):
            def __getitem__(self, item):
                return item

        class NotRequired(metaclass=_CompatNotRequiredMeta):  # type: ignore
            """Fallback no-op NotRequired for older Python versions."""

            pass


class StageSummaryEntry(TypedDict):
    """
    Typed manifest entry that downstream services can rely on.

    Fields are intentionally descriptive to avoid hard-coded logic in the
    evaluator service.
    """

    key: str
    title: str
    description: str
    data_source: str
    completion_rule: str  # Legacy: kept for documentation
    completion_field: str  # Legacy: kept for documentation
    completion_type: str  # Type: "file", "file_name_like", "adminfile", "consult", "quiz", "manifest_stage", "device_status"
    completion_args: Dict[str, Any]  # Arguments for the completion_type function
    guidance: str
    prerequisites: List[str]
    skip_if: NotRequired[List[str]]  # NEW: Stage keys that, if completed, allow this stage to be skipped
    optional: NotRequired[bool]  # NEW: Whether this stage is optional (can be skipped)
    validation_function: NotRequired[str]  # Optional: name of specific validation function
    llm_context_tag: NotRequired[str]
    feature_flag: NotRequired[str]


STAGE_SUMMARY_MANIFEST: List[StageSummaryEntry] = [
    # ===========================================================================
    # REPORT-BASED SKIP LOGIC:
    # If a Vizbriz report exists, it means all prerequisite data was available.
    # Therefore, earlier stages can be auto-skipped when a later report is present.
    #
    # Report Hierarchy (each report implies earlier stages were completed):
    #   - Level 1 (Screening): Quiz data was collected
    #   - Level 3 (Data Assessment): CBCT/imaging data was collected  
    #   - Level 4 (Full Data Report): All clinical data collected, OSA diagnosed
    #   - Level 5+ (Follow-up): Treatment has been delivered
    # ===========================================================================
    {
        "key": "quiz_completion",
        "title": "Quiz Completion",
        "description": "Patient has completed the basic or advanced sleep quiz.",
        "data_source": "conversion_quiz",
        "completion_rule": "quiz_type IN ('basic_quiz', 'advanced_quiz') AND user_id = patient_id",
        "completion_field": "created_at",
        "completion_type": "quiz",
        "completion_args": {"quiz_types": ["basic_quiz", "advanced_quiz"]},
        "guidance": "Patient must complete and submit the sleep quiz. Send quiz link if not completed.",
        "prerequisites": [],
        "skip_if": ["level_1_report_screening", "osa_report_ready"],  # If any report exists, quiz data was collected
        "optional": True,
        "llm_context_tag": "assessment",
    },
    {
        "key": "level_1_report_screening",
        "title": "Level 1 Report - Screening",
        "description": "Level 1 report (screening) has been uploaded and is available for review.",
        "data_source": "adminfiles",
        "completion_rule": "LOWER(name) LIKE '%level_1%' AND patient_id = patient_id",
        "completion_field": "upload_date",
        "completion_type": "adminfile_name_like",
        "completion_args": {"name_pattern": "level_1"},
        "guidance": "Upload Level 1 report (screening) under Reports & Files. Generated by Vizbriz, so prerequisites are already met.",
        "prerequisites": [],
        "skip_if": ["osa_report_ready"],  # If Level 4 exists, Level 1 data was already processed
        "optional": True,
        "llm_context_tag": "screening",
    },
    {
        "key": "sleep_study_scheduled",
        "title": "Sleep Study Scheduled",
        "description": "Sleep study consultation has been scheduled with sleep doctor (ENT).",
        "data_source": "patient_consult_schedule",
        "completion_rule": "consult_type = 'sleep_doctor' AND patient_id = patient_id",
        "completion_field": "scheduled_datetime",
        "completion_type": "consult",
        "completion_args": {"consult_type": "sleep_doctor"},
        "guidance": "Schedule consultation with sleep doctor (ENT) to order sleep study. If patient already has sleep test completed, this stage can be skipped.",
        "prerequisites": ["level_1_report_screening"],
        "skip_if": ["sleep_test_completed", "osa_report_ready"],  # Can skip if sleep test done or Level 4 exists
        "optional": True,
        "llm_context_tag": "scheduling",
    },
    {
        "key": "sleep_test_completed",
        "title": "Sleep Test Completed",
        "description": "Sleep study report is available in patient files.",
        "data_source": "files",
        "completion_rule": "subcategory = 'sleep-test' AND patient_id = patient_id",
        "completion_field": "upload_date",
        "completion_type": "file",
        "completion_args": {"subcategory": "sleep-test"},
        "guidance": "Upload sleep test report under Reports & Files > Sleep Tests.",
        "prerequisites": ["sleep_study_scheduled"],
        "skip_if": ["osa_report_ready"],  # If Level 4 exists, sleep test data was available
        "optional": True,
        "llm_context_tag": "diagnostics",
    },
    {
        "key": "schedule_sleep_test_review",
        "title": "Schedule Sleep Test Review",
        "description": "Follow-up consultation scheduled to review sleep test results.",
        "data_source": "patient_consult_schedule",
        "completion_rule": "consult_type = 'followup_sleep_doctor' AND patient_id = patient_id",
        "completion_field": "scheduled_datetime",
        "completion_type": "consult",
        "completion_args": {"consult_type": "followup_sleep_doctor"},
        "guidance": "Schedule follow-up consultation with sleep specialist (EP doctor) to review test results.",
        "prerequisites": ["sleep_test_completed"],
        "skip_if": ["sleep_doctor_followup_completed", "osa_report_ready"],  # Can skip if followup done or Level 4 exists
        "optional": True,
        "llm_context_tag": "scheduling",
    },
    {
        "key": "sleep_doctor_followup_completed",
        "title": "Sleep Doctor Followup and Prescription",
        "description": "Follow-up consultation with sleep specialist has been completed and prescription provided.",
        "data_source": "patient_consult_schedule",
        "completion_rule": "consult_type = 'followup_sleep_doctor' AND status = 'completed' AND patient_id = patient_id",
        "completion_field": "completed_datetime",
        "completion_type": "consult",
        "completion_args": {"consult_type": "followup_sleep_doctor", "status": "completed"},
        "guidance": "Mark the follow-up consultation as completed after OSA diagnosis is confirmed and prescription is provided.",
        "prerequisites": ["schedule_sleep_test_review"],
        "skip_if": ["dental_sleep_doctor_consult_scheduled", "osa_report_ready"],  # Can skip if dental consult scheduled or Level 4 exists
        "optional": True,
        "llm_context_tag": "consultation",
    },
    {
        "key": "dental_sleep_doctor_consult_scheduled",
        "title": "Dental Sleep Doctor Consult Scheduled",
        "description": "Consultation with dental sleep specialist has been scheduled.",
        "data_source": "patient_consult_schedule",
        "completion_rule": "consult_type = 'dental_sleep_doctor' AND patient_id = patient_id",
        "completion_field": "scheduled_datetime",
        "completion_type": "consult",
        "completion_args": {"consult_type": "dental_sleep_doctor"},
        "guidance": "Schedule consultation with dental sleep specialist to discuss oral appliance treatment options.",
        "prerequisites": ["sleep_doctor_followup_completed"],
        "skip_if": ["met_with_dental_sleep_expert", "cbct_observation_report_uploaded", "osa_report_ready"],  # Can skip if consult done, Level 3 or Level 4 exists
        "optional": True,
        "llm_context_tag": "scheduling",
    },
    {
        "key": "cbct_observation_report_uploaded",
        "title": "Level 3 Report - Data Assessment",
        "description": "Level 3 report (data assessment) has been uploaded and is available for review.",
        "data_source": "adminfiles",
        "completion_rule": "LOWER(name) LIKE '%level_3%' AND patient_id = patient_id",
        "completion_field": "upload_date",
        "completion_type": "adminfile_name_like",
        "completion_args": {"name_pattern": "level_3"},
        "guidance": "Upload Level 3 report (data assessment) under Reports & Files. Generated by Vizbriz, so prerequisites are already met.",
        "prerequisites": [],
        "skip_if": ["osa_report_ready"],  # If Level 4 exists, Level 3 data was already processed
        "optional": True,
        "llm_context_tag": "imaging",
    },
    {
        "key": "intraoral_scan_uploaded",
        "title": "Intraoral Scan Uploaded",
        "description": "Intraoral scan files (STL format) have been uploaded.",
        "data_source": "files",
        "completion_rule": "category = 'intra_oral_scan' AND patient_id = patient_id",
        "completion_field": "upload_date",
        "completion_type": "file",
        "completion_args": {"category": "intra_oral_scan"},
        "guidance": "Upload intraoral scan files (STL format) under Reports & Files > Intraoral Scans. Typically taken when patient meets with dental sleep expert.",
        "prerequisites": [],  # Mandatory but not dependent on previous stages
        "skip_if": ["osa_report_ready"],  # If Level 4 exists, intraoral data was available for the report
        "optional": True,
        "llm_context_tag": "imaging",
    },
    {
        "key": "hipaa_consent_signed",
        "title": "Consent Forms Signed",
        "description": "Patient has signed HIPAA consent and treatment authorization forms.",
        "data_source": "files",
        "completion_rule": "subcategory = 'billing' AND (name LIKE '%HIPAA%' OR name LIKE '%consent%') AND patient_id = patient_id",
        "completion_field": "upload_date",
        "completion_type": "file_name_like",
        "completion_args": {"subcategory": "billing", "name_keywords": ["HIPAA", "consent"]},
        "guidance": "Upload signed HIPAA consent form under Reports & Files > Billing. Can be signed at any time.",
        "prerequisites": [],  # Can be signed at any time, no prerequisites
        "skip_if": ["osa_report_ready"],  # If Level 4 exists, patient consented to treatment
        "optional": True,  # Stage 11: Not mandatory
        "llm_context_tag": "compliance",
    },
    {
        "key": "met_with_dental_sleep_expert",
        "title": "Met with Dental Sleep Expert",
        "description": "Consultation with dental sleep specialist has been completed.",
        "data_source": "patient_consult_schedule",
        "completion_rule": "consult_type = 'dental_sleep_doctor' AND status = 'completed' AND patient_id = patient_id",
        "completion_field": "completed_datetime",
        "completion_type": "consult",
        "completion_args": {"consult_type": "dental_sleep_doctor", "status": "completed"},
        "guidance": "Mark the dental sleep expert consultation as completed after treatment plan is discussed.",
        "prerequisites": ["dental_sleep_doctor_consult_scheduled"],  # Only requires the consultation to be scheduled
        "skip_if": ["osa_report_ready"],  # If Level 4 exists, dental consultation was completed
        "optional": True,
        "llm_context_tag": "consultation",
    },
    {
        "key": "osa_report_ready",
        "title": "Level 4 Report - Full Data Report",
        "description": "Level 4 report (full data report) with OSA diagnosis and treatment plan is ready.",
        "data_source": "adminfiles",
        "completion_rule": "LOWER(name) LIKE '%level_4%' AND patient_id = patient_id",
        "completion_field": "upload_date",
        "completion_type": "adminfile_name_like",
        "completion_args": {"name_pattern": "level_4"},
        "guidance": "Upload Level 4 report (full data report) under Reports & Files. Generated by Vizbriz, so prerequisites are already met.",
        "prerequisites": [],
        "llm_context_tag": "reporting",
    },
    {
        "key": "order_oral_appliance",
        "title": "Order Oral Appliance",
        "description": "Custom oral appliance has been ordered from laboratory.",
        "data_source": "patient_device_order",
        "completion_rule": "device_type = 'oral_appliance' AND patient_id = patient_id AND order_date IS NOT NULL",
        "completion_field": "order_date",
        "completion_type": "device_order",
        "completion_args": {"device_type": "oral_appliance"},
        "guidance": "Order the custom oral appliance after OSA report approval and all required documents are uploaded.",
        "prerequisites": ["osa_report_ready"],
        "llm_context_tag": "ordering",
    },
    {
        "key": "schedule_oral_appliance_delivery",
        "title": "Schedule Oral Appliance Delivery",
        "description": "Appliance delivery appointment has been scheduled with patient.",
        "data_source": "patient_consult_schedule",
        "completion_rule": "consult_type = 'oral_appliance_delivery' AND patient_id = patient_id",
        "completion_field": "scheduled_datetime",
        "completion_type": "consult",
        "completion_args": {"consult_type": "oral_appliance_delivery"},
        "guidance": "Schedule appointment for oral appliance delivery and fitting with patient.",
        "prerequisites": ["order_oral_appliance"],
        "llm_context_tag": "scheduling",
    },
    {
        "key": "oral_appliance_delivery_completed",
        "title": "Oral Appliance Delivery Completed",
        "description": "Oral appliance has been delivered and fitted to patient.",
        "data_source": "patient_device_order",
        "completion_rule": "device_type = 'oral_appliance' AND patient_id = patient_id AND arrival_date IS NOT NULL",
        "completion_field": "arrival_date",
        "completion_type": "device_delivery",
        "completion_args": {"device_type": "oral_appliance"},
        "guidance": "Record when the oral appliance has been delivered (arrival_date in device order).",
        "prerequisites": ["schedule_oral_appliance_delivery"],
        "llm_context_tag": "delivery",
    },
    {
        "key": "follow_up_sleep_test_after_delivery",
        "title": "Level 5 First Follow-up Report",
        "description": "Level 5 first follow-up report has been completed after appliance delivery.",
        "data_source": "adminfiles",
        "completion_rule": "LOWER(name) LIKE '%level_5%' AND patient_id = patient_id",
        "completion_field": "upload_date",
        "completion_type": "adminfile_name_like",
        "completion_args": {"name_pattern": "level_5"},
        "guidance": "Upload Level 5 first follow-up report under Reports & Files to assess treatment effectiveness. Generated by Vizbriz, so prerequisites are already met.",
        "prerequisites": ["oral_appliance_delivery_completed"],
        "skip_if": ["level_6_report_second_followup", "level_7_report_osa_transitional_reassessment"],  # If later follow-up exists, this was done
        "optional": True,
        "llm_context_tag": "diagnostics",
    },
    {
        "key": "level_6_report_second_followup",
        "title": "Level 6 Report - 2nd Follow-up",
        "description": "Level 6 report (2nd follow-up) has been completed.",
        "data_source": "adminfiles",
        "completion_rule": "LOWER(name) LIKE '%level_6%' AND patient_id = patient_id",
        "completion_field": "upload_date",
        "completion_type": "adminfile_name_like",
        "completion_args": {"name_pattern": "level_6"},
        "guidance": "Upload Level 6 report (2nd follow-up) under Reports & Files to assess ongoing treatment effectiveness. Generated by Vizbriz, so prerequisites are already met.",
        "prerequisites": [],
        "skip_if": ["level_7_report_osa_transitional_reassessment"],  # If Level 7 exists, Level 6 was done
        "optional": True,
        "llm_context_tag": "diagnostics",
    },
    {
        "key": "level_7_report_osa_transitional_reassessment",
        "title": "Level 7 Report - OSA Transitional Re-assessment Report",
        "description": "Level 7 report (OSA transitional re-assessment) has been completed. Requires a sleep test to evaluate treatment efficacy.",
        "data_source": "adminfiles",
        "completion_rule": "LOWER(name) LIKE '%level_7%' AND patient_id = patient_id",
        "completion_field": "upload_date",
        "completion_type": "adminfile_name_like",
        "completion_args": {"name_pattern": "level_7"},
        "guidance": "Upload Level 7 report (OSA transitional re-assessment) under Reports & Files with sleep test results to evaluate long-term treatment efficacy and outcomes. Generated by Vizbriz, so prerequisites are already met.",
        "prerequisites": [],
        "llm_context_tag": "diagnostics",
    },
]


def get_stage_summary_manifest() -> List[StageSummaryEntry]:
    """
    Accessor that returns a mutable copy of the manifest.

    The copy prevents accidental in-place mutation of the module-level
    definition while allowing callers to modify their working set.
    """

    return [entry.copy() for entry in STAGE_SUMMARY_MANIFEST]


