import os
import re
import shutil
from pathlib import Path


TARGET_KEYS = [
    # DB
    "DB_USERNAME",
    "DB_PASSWORD",
    "DB_HOST",
    "DB_PORT",
    "DB_NAME",
    # AWS / S3
    "AWS_ACCESS_KEY_ID",
    "AWS_SECRET_ACCESS_KEY",
    "AWS_REGION",
    "S3_BUCKET_NAME",
]


def _mask(key: str, value: str) -> str:
    if any(s in key for s in ("PASSWORD", "SECRET", "KEY")):
        return f"{value[:4]}... (truncated)"
    return value


def main() -> int:
    repo_root = Path(__file__).resolve().parents[1]
    init_path = repo_root / "flask_app" / "__init__.py"
    env_path = repo_root / "env" / "app.env"
    env_path.parent.mkdir(parents=True, exist_ok=True)

    if not init_path.exists():
        print(f"ERROR: init file not found: {init_path}")
        return 1

    init_text = init_path.read_text(encoding="utf-8", errors="replace")

    # Match patterns like:
    # os.environ['DB_USERNAME'] = 'admin'
    pattern = re.compile(
        r"os\.environ\[\s*['\"](?P<key>[A-Z0-9_]+)['\"]\s*\]\s*=\s*['\"](?P<value>.*?)['\"]"
    )

    extracted: dict[str, str] = {}
    for m in pattern.finditer(init_text):
        key = m.group("key")
        if key in TARGET_KEYS and key not in extracted:
            extracted[key] = m.group("value")

    missing = [k for k in TARGET_KEYS if k not in extracted]
    if missing:
        print("ERROR: Could not extract the following keys from flask_app/__init__.py:")
        for k in missing:
            print(f"- {k}")
        print("\nThis script only extracts hardcoded assignments like:")
        print("os.environ['DB_USERNAME'] = '...'")
        return 1

    if env_path.exists():
        backup_path = env_path.with_suffix(env_path.suffix + ".bak")
        shutil.copy2(env_path, backup_path)
        print(f"Backed up existing env file to: {backup_path}")

    lines: list[str] = []
    lines.append("# GENERATED FILE - contains secrets")
    lines.append("# Generated by: scripts/extract_init_db_s3_to_env.py")
    lines.append("# Source: flask_app/__init__.py")
    lines.append("# Do NOT commit this file.")
    lines.append("")
    for key in TARGET_KEYS:
        # Write raw values (including secrets) into env file
        lines.append(f"{key}={extracted[key]}")
    lines.append("")

    env_path.write_text("\n".join(lines), encoding="utf-8")

    # Best-effort: restrict permissions on linux (ignore failures on unsupported FS)
    try:
        os.chmod(env_path, 0o600)
    except Exception:
        pass

    print(f"Wrote: {env_path}")
    print("\nExtracted values:")
    for key in TARGET_KEYS:
        print(f"- {key}: {_mask(key, extracted[key])}")

    print("\nNext: run the validator:")
    print(f"python {repo_root / 'scripts' / 'validate_env_file_access.py'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())

